In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from data_processing import preprocess_data

In [38]:
data_training = pd.read_csv(r'data_entrenamiento.csv')

In [39]:
# Aplicar transformaciones
df_train2 = preprocess_data(data_training)

c:\Users\elvynda\OneDrive - ADMINISTRADORA DE RIESGOS DE SALUD PALIC\Desktop\Proyect_comercial\data_processing.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [30]:
df_train2

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0.0,0.0,0.0,0.0,0.112676,0.0,0.0,0.401096,0.060120,1.0,...,True,False,True,False,True,False,False,False,False,True
1,1.0,0.0,0.0,0.0,0.352113,1.0,0.0,0.431490,0.180373,0.0,...,False,False,False,False,False,True,False,False,True,False
2,0.0,0.0,0.0,0.0,0.028169,1.0,1.0,0.515197,0.023263,0.0,...,False,False,True,False,True,True,False,False,True,False
3,1.0,0.0,0.0,0.0,0.084507,1.0,0.0,0.551570,0.057830,1.0,...,False,False,False,False,False,False,False,False,True,False
4,1.0,0.0,1.0,1.0,0.929577,1.0,1.0,0.420030,0.454059,0.0,...,True,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4917,1.0,0.0,0.0,0.0,0.028169,1.0,0.0,0.320379,0.013663,0.0,...,False,False,False,False,False,False,False,False,False,False
4918,0.0,0.0,0.0,0.0,0.704225,1.0,1.0,0.929248,0.655947,0.0,...,True,False,True,False,True,True,False,False,True,False
4919,1.0,0.0,0.0,0.0,0.112676,1.0,1.0,0.626806,0.088346,0.0,...,False,False,False,False,False,False,False,False,True,False
4920,0.0,0.0,0.0,0.0,0.690141,1.0,0.0,0.014948,0.111955,0.0,...,False,True,False,True,False,True,False,False,False,False
4921,1.0,1.0,1.0,0.0,0.267606,1.0,1.0,0.552068,0.166704,1.0,...,False,False,False,False,False,False,False,False,True,False